---
driver:
  name: dokken
  chef_version: latest
  privileged: true

driver_config:
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>
  use_internal_docker_network: true

transport:
  name: dokken

provisioner:
  name: dokken
  cookbook_paths:
    - ./test/cookbooks
  attributes:
    cwlogs:
      region: us-west-1
      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd

verifier:
  root_path: '/opt/verifier'
  sudo: false

suites:
  - name: default
    run_list:
      - recipe[cwlogs]
      - recipe[cwlogs_test]
