---
driver:
  name: docker
  use_sudo: false
  dns:
    - 8.8.8.8
    - 8.8.4.4

driver_config:
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>

provisioner:
  name: chef_zero
  cookbook_paths:
    - ./test/cookbooks
  attributes:
    cwlogs:
      region: us-west-1
      aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
    driver:
      name: vagrant
      box: bento/ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[cwlogs]
      - recipe[cwlogs_test]
